USE productsdb;
CREATE TABLE Customers
(
    Id INT IDENTITY PRIMARY KEY,
	FirstName NVARCHAR(30) NOT NULL,
    LastName NVARCHAR(30) NOT NULL,
    Patronymic NVARCHAR(30) NOT NULL,
    City NVARCHAR(30) NOT NULL
);
CREATE TABLE Sellers
(
    Id INT IDENTITY PRIMARY KEY,
	    FirstName NVARCHAR(30) NOT NULL,
    LastName NVARCHAR(30) NOT NULL,
    Patronymic NVARCHAR(30) NOT NULL,
    City NVARCHAR(30) NOT NULL,
	Commission REAL NOT NULL
);
CREATE TABLE Orders
(
    Id INT IDENTITY PRIMARY KEY,
	Description NVARCHAR(200),
	Sum MONEY NOT NULL CHECK(Sum > 0),
    CustomerId INT NOT NULL REFERENCES Customers(Id) ON DELETE CASCADE,
	SellerId INT NOT NULL REFERENCES Sellers(Id) ON DELETE CASCADE,
	CreatedAt DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE OrderHistory 
(
    Id INT IDENTITY PRIMARY KEY,
    Operation NVARCHAR(200) NOT NULL,
	CustomerId INT NOT NULL REFERENCES Customers(Id) ON DELETE CASCADE ON UPDATE CASCADE,
	SellerId INT NOT NULL REFERENCES Sellers(Id) ON DELETE CASCADE ON UPDATE CASCADE,
	OrderDate DATETIME NOT NULL,
	CreatedAt DATETIME NOT NULL DEFAULT GETDATE()
);